---
keys:
  - &sarw age1gqkpvcczyezrcq5dterejspewfv443awwynuf48rgql48c4y34xsmdjp4z
  - &mithrix age1sklfnht5lgc9psmrzrujapfhyclzc72argvk4hya67u3cdtag58smg0vhq
creation_rules:
  - path_regex: secrets/sarw/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/aurelionite/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/grovetender/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/mithrix/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mithrix
