---
keys:
  - &sarw age1r6wsle7rqefqla07fyxdwuasrxp3j50xxpzdhg8087r3qamsrsms856uy3
  - &mithrix age1sklfnht5lgc9psmrzrujapfhyclzc72argvk4hya67u3cdtag58smg0vhq
creation_rules:
  - path_regex: secrets/sarw/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/aurelionite/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/grovetender/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *sarw
  - path_regex: secrets/mithrix/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mithrix
